# Generated by Django 4.1.4 on 2023-01-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_carryandcomps_body_carryandcomps_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryandcomps',
            name='body',
            field=models.JSONField(default='yes'),
            preserve_default=False,
        ),
    ]
